language: python
python:
  - "3.7"
  - "3.8"
  - "nightly"

jobs:
  allow_failures:
    - python: "nightly"

env:
  - SQLALCHEMY_DATABASE_URI="sqlite:///:memory:"

before_install:
  - cd backend/

# command to install dependencies
install:
  - pipenv install --dev --deploy

# command to run tests
script:
  - flake8
  - pytest