language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - cd backend/

# command to install dependencies
install:
  - pip install pipenv flake8 pytest
  - pipenv install --system --deploy

# command to run tests
script:
  - flake8
  - pytest