language: python
python:
  - "3.7"
  - "3.8"
  - "nightly"

jobs:
  allow_failures:
    - python: "nightly"

env:
  global:
    - SQLALCHEMY_DATABASE_URI="sqlite:///:memory:"
    - CODECOV_TOKEN="fc5bf719-41db-4351-8fbd-59308bdd9d19"

before_install:
  - cd backend/

# command to install dependencies
install:
  - pipenv install --dev --deploy

# command to run tests
script:
  - flake8
  - pytest --cov=api --cov-report=xml

after_success:
  - curl -s https://codecov.io/bash | bash
