version: '3.7'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: frontend.dockerfile
    restart: unless-stopped
    ports:
      - 80:80

  backend:
    build: 
      context: ./backend
      dockerfile: backend.dockerfile
    restart: unless-stopped
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:${POSTGRES_PASSWORD}@db/postgres
    depends_on:
      - db
    ports:
      - 8080:80

  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
